image: node:14.17.5
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.2.3
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - public
  only:
    - master
    - pages